# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Puntada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('costo_puntada', models.FloatField()),
                ('status', models.IntegerField()),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntadas.Empleado')),
                ('puntada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntadas.Puntada')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='puntadas',
            field=models.ManyToManyField(through='puntadas.Registro', to='puntadas.Puntada'),
        ),
    ]
